CREATE DATABASE customers_behaviour;

USE customers_behaviour;
SELECT 
    *
FROM
    customer_purchases
LIMIT 10;

SET SQL_SAFE_UPDATES = 0;

UPDATE customer_purchases 
SET 
    `Frequency of Purchases` = CASE `Frequency of Purchases`
        WHEN 'Fortnightly' THEN 14
        WHEN 'Weekly' THEN 7
        WHEN 'Monthly' THEN 30
        WHEN 'Quarterly' THEN 90
        WHEN 'Bi-Weekly' THEN 14
        WHEN 'Annually' THEN 365
        WHEN 'Every 3 Months' THEN 90
        ELSE `Frequency of Purchases`
    END;


-- Q1 What is total revenue generated by male vs female customers?
SELECT 
    gender, SUM(`Purchase Amount (USD)`) AS Revenue_Generated
FROM
    customer_purchases
GROUP BY gender;

-- Q2 Which customers used a discount but still not spent more than the average purchase amount
SELECT 
    `Customer Id`, `Purchase Amount (USD)`
FROM
    customer_purchases
WHERE
    (`Discount Applied`) = 'Yes'
        AND `Purchase Amount (USD)` >= (SELECT 
            AVG(`Purchase Amount (USD)`)
        FROM
            customer_purchases);

-- Q.3 Which are the top 5 products with highest average review rating?
SELECT DISTINCT
    `Item Purchased`,
    ROUND(AVG(`Review Rating`), 2) AS `Average Product Rating`
FROM
    customer_purchases
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;

-- Q.4 Compare the average Purchase Amounts Between Standard and Express Shipping 
SELECT 
    `Shipping Type`, AVG(`Purchase Amount (USD)`)
FROM
    customer_purchases
WHERE
    `Shipping Type` IN ('Standard' , 'Express')
GROUP BY `Shipping Type`;

-- Q.5 Do subscribed customers spend more? Compare avrage spend and total revenue between subsribers and non-subscribers
SELECT 
    `Subscription Status`,
    COUNT(`Subscription Status`),
    AVG(`Purchase Amount (USD)`) AS AVG_Purchase_Amount,
    SUM(`Purchase Amount (USD)`) AS Total_Purchase_Amount
FROM
    customer_purchases
WHERE
    `Subscription Status` IN ('Yes' , 'No')
GROUP BY `Subscription Status`;

-- Q.6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    `Item Purchased`,
    ROUND(100 * SUM(CASE
                WHEN `Discount Applied` = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer_purchases
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q.7  Segment customers into New,Returning, and Loyal based on their total number of previous purchses and show the count of each segment.
with customer_type as (
select `Customer ID`,`Previous Purchases`,
case 
	when `Previous Purchases` = 1 then 'New'
	when `Previous Purchases` between 2 and 10 then 'Returning'
    else 'Loyal'
    end as 'Customer_Segment'
from customer_purchases )

select customer_segment,count(*) as "Number Of Customers"
from customer_type
group by customer_segment;

-- Q.8 What are the top three most purchased products within each category
with item_counts as(
select `Category`,`Item Purchased`,count(`Customer Id`) as Total_Orders,
Row_Number() Over(partition by `Category` order by count(`Customer Id`) DESC) as item_rank
from customer_purchases
group by `Category`,`Item Purchased`)

select item_rank,`Category`,`Item Purchased`,Total_Orders
from item_counts
where item_rank <=3;

-- Q.9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? 
SELECT 
    `Subscription Status`, COUNT(`Customer Id`) AS repeat_buyers
FROM
    customer_purchases
WHERE
    `Previous Purchases` > 5
GROUP BY `Subscription Status`;

ALTER TABLE customer_purchases
ADD COLUMN age_group VARCHAR(20);


UPDATE customer_purchases 
SET 
    age_group = CASE
        WHEN Age <= 25 THEN 'Young_Adult'
        WHEN Age > 25 AND Age <= 40 THEN 'Adult'
        WHEN Age > 40 AND Age <= 55 THEN 'Middle-aged'
        ELSE 'Senior'
    END;


-- Q10. What is the revenue contribution of Each Age Group?
SELECT 
    age_group, SUM(`Purchase Amount (USD)`) AS Revenue_Generated
FROM
    customer_purchases
GROUP BY age_group;

SELECT 
    *
FROM
    customer_purchases
LIMIT 10;



